parallelism: 4
executor:
  name: win/default
steps:
  - checkout
  - run:
      command: ./scripts/assert-changed-files.sh "packages/*|.circleci/*"
      shell: bash.exe
  - restore_cache:
      key: yarn-offline-cache-v0.0
  - run: yarn --frozen-lockfile --prefer-offline --link-duplicates
  - save_cache:
      paths:
        - ./.yarn/yarn-offline-cache/
      key: yarn-offline-cache-v0.0
  - run:
      name: Run tests
      command: yarn jest --ci --runInBand ((yarn jest --listTests) | Foreach-Object {$_ -replace '.*\\packages', 'packages'} | Foreach-Object {$_ -replace '\', '/'} | circleci tests split --split-by=timings)
      environment:
        NODE_OPTIONS: --max-old-space-size=2048
        GENERATE_JEST_REPORT: true
        JEST_JUNIT_OUTPUT_DIR: ./test-results/jest-node/
        JEST_JUNIT_OUTPUT_NAME: results.xml
  - store_test_results:
      path: ./test-results/jest-node/
